preparingforexams/hhh-diff-bot

- .github/workflows/publish.yml
- .kubernetes/manifest.yaml
- main.py
- telegram_bot/bot.py
digitalocean only supports `ReadWriteOnce` and volumes must be at least `1Gi`.
State should not be set to empty on a decoding error if there are defaults in `__init__`.
> Several updates

- telegram_bot/bot.py
- telegram_bot/decorators.py
Also update sort and groupby to compare by lowercase -> this was a bug before.
> Update logic for replacing the chat title

- .github/workflows/publish.yml
- .kubernetes/manifest.yaml
- telegram_bot/bot.py
I'm going to test the PVC update sometime this week.
> Bugfixes and show total count

- telegram_bot/bot.py
> Remove welcome and goodbye messages

- .github/workflows/publish.yml
Based on this: https://stackoverflow.com/a/59482124
> This'll definitly, most likely, hopefully work

- .github/workflows/publish.yml
See https://github.com/torbencarstens/hhh-diff-bot/runs/1570926734 for error
> Update `delete rs [...]` command

- telegram_bot/bot.py
This way it's visible in the pinned message
> Move 'total_group_count' to the beginning of the message

- .github/workflows/publish.yml
- commands.md
- main.py
- telegram_bot/bot.py
- telegram_bot/chat.py
> Add invite links to chat

- commands.md
- main.py
- telegram_bot/bot.py
- telegram_bot/chat.py
- telegram_bot/decorators.py
> Add `delete_chat_by_id` command

- main.py
- telegram_bot/bot.py
kicked from chat (reduced message count)
-> delete old unused messages
added to chat (increased message count)
-> send a new set of message
Closes #15
> Split text into multiple messages

- telegram_bot/bot.py
> Use 'chat.id' if 'migrate_to_chat_id' is 'None'

- telegram_bot/bot.py
> Update message on update of invite link

- telegram_bot/bot.py
> Add https://t.me/.* as possible link format

- telegram_bot/bot.py
> Send message when bot joins a group/chat is created

- telegram_bot/bot.py
if `pinned_message_id` is some -> unpin message
always pin the first message when sending a new message, ignore on edit.
is this a shitty impl? yes
Closes #40
> Add pinning support

- main.py
- telegram_bot/bot.py
> Remove unknown command handler

- telegram_bot/chat.py
- telegram_bot/decorators.py
> Add debug output and pull apart expression

- telegram_bot/decorators.py
> Only check for invite links in group chats

- .github/workflows/lint_build.yml
- .gitignore
- main.py
- requirements.txt
- telegram_bot/bot.py
- telegram_bot/chat.py
- telegram_bot/decorators.py
> Update to python-telegram-sdk==20.0

- commands.md
- main.py
- telegram_bot/bot.py
- telegram_bot/chat.py
- telegram_bot/decorators.py
- telegram_bot/logger.py
Has the added benefit of complicating the `@Command` decorator further
> Add gatekeeping

- .github/workflows/build_publish.yml
- .github/workflows/lint_build.yml
Reverts preparingforexams/hhh-diff-bot#125
> Revert "Update actions/checkout action to v4"

- telegram_bot/decorators.py
> Remove old argument
